import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/header";
import Logo from "./components/logo";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJS app for eCommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
           <body className={inter.className}> <><Logo/></><><NavBar/></>{children}</body>
    </html>
  );
}
